### ISSUE TITLE
Launch Stealth Error

### ISSUE THREAD

**Issue by mangfu26** [minhlucvan/n8n-nodes-browserless#19]
I launched a Browserless container locally using Docker Compose. Here’s the content of my docker-compose.yaml file:

```yaml
yaml
services:
  browserless:
    image: ghcr.io/browserless/chromium:latest
    container_name: browserless-chromium
    ports:
      - 3000:3000
    environment:
      - TOKEN=xxxxxxxxxxxxxxx
      - CONCURRENT=10
      - TIMEOUT=60000
    restart: unless-stopped
```

I added two Launch options in the Browserless node:
- Headless: False
- Stealth: True

However, after executing the steps, I encountered the following error:

> Bad request - please check your parameters
> Request failed with status code 400

![Image](https://github.com/user-attachments/assets/1500ee96-ccee-4e1d-aa21-9e350fae4271)

I checked the logs of the `browserless-chromium` container and found the following error:  

```bash  
browserless-chromium  |   browserless.io:server:trace  Authorizing HTTP request to "/screenshot?timeout=0&blockAds=true&launch%5Bstealth%5D=true&token=s6JVL8FxdED4imcX" +0ms  
browserless-chromium  |   browserless.io:server:trace  Validating route query-params with QUERY schema +1ms  
browserless-chromium  |   browserless.io:server:error  HTTP query-params contain errors sending 400:"launch[stealth]" is not allowed +2s  
```    

How should I resolve this error?

I would be extremely grateful if you could provide a solution.
